services: 

  app:
    image: leetcode
    ports:
      - "3000:3000"

    depends_on:
      - redis
      - postgres-primary

    environment: 
      DATABASE_URL: postgresql://root:root@postgres-primary:5432/leetcodeclone
      REDIS_URL: redis://redis:6379


  redis:
      image: redis:7.4.7
      container_name: leetcodeClone-server
      restart: unless-stopped 
      ports:
        - "6379:6379"

      volumes:
        - redis_data:/data

  postgres-primary:
      image: postgres:16
      container_name: leetcode-primary
      ports:
        - "5432:5432"
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: leetcodeclone

      restart: unless-stopped
      volumes:
        - postgres_primary_data:/var/lib/postgresql/data
      


volumes:
  postgres_primary_data:
  redis_data: